# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: veritascrmod 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "veritascrmod"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Edmund Highcock"]
  s.date = "2016-08-08"
  s.description = "A CodeRunner module for the Veritas Vlasov Solver"
  s.email = "edmundhighcock@users.sourceforge.net"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/veritascrmod.rb",
    "lib/veritascrmod/namelists.rb",
    "lib/veritascrmod/veritas.rb",
    "sync_variables/helper.rb",
    "sync_variables/sync_variables.rb",
    "test/helper.rb",
    "test/test.in",
    "test/test_veritas.rb"
  ]
  s.homepage = "http://github.com/coderunner-framework/veritascrmod"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.8"
  s.summary = "A CodeRunner module for the Veritas Vlasov Solver"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<coderunner>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<narray>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<juwelier>, ["~> 2.1.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<coderunner>, [">= 1.0.0"])
      s.add_dependency(%q<narray>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<juwelier>, ["~> 2.1.0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<coderunner>, [">= 1.0.0"])
    s.add_dependency(%q<narray>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<juwelier>, ["~> 2.1.0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

